channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.*
  - pandas
  - pytest
  - scikit-bio
  - prodigal
  - mmseqs2
  - hmmer
  - trnascan-se >=2
  - networkx
  - sqlalchemy
  - barrnap
