channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.*
  - pandas
  - pytest
  - scikit-bio
  - prodigal
  - mmseqs2!=10.6d92c
  - hmmer
  - trnascan-se >=2
  - sqlalchemy
  - barrnap
  - altair
  - openpyxl
  - networkx
  - ruby
  - parallel
